apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
       - name: identity
         image: docker.io/sajadkiani/identity:1.0.6
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: identitynp
spec:
  type: NodePort
  selector: 
    app: identity
  ports:
   - name:  identitynp
     port:  5002
     protocol: TCP
     targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: identity-clusterip
spec:
  type: ClusterIP
  selector:
    app: identity
  ports:
  - name: identity-port
    protocol: TCP
    port: 5002
    targetPort: 80
