apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
       - name: identity
         image: docker.io/sajadkiani/identity:1.0.1
         imagePullPolicy: IfNotPresent
         ports:
           - containerPort: 5002